### PR TITLE
Protect branch with required checks

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Require successful status checks and at least one review for enabling merge button.

## How was this patch tested?

Can only be tested with another PR after merge.  Hence opening in experimental repo.

### CODE REVIEW

**Review by cxorm — APPROVED** [review]
Thank you @adoroszlai for the idea.
I'm +1 for it.

BTW I have an question not related to this PR, 
could you be so kind as to let me know the process of contributing this repo ? (Just as filing a Jira or some other method), thanks.

**Comment by elek** [comment]
> BTW I have an question not related to this PR,
> could you be so kind as to let me know the process of contributing this repo ? (Just as filing a Jira or some other method), thanks.

Yes, just use the regular contribution process. New issues can be sub-issue of https://issues.apache.org/jira/browse/HDDS-4977 (to make it easier to find them later and that issues is already watched by a few people interested).

AFAIK there is now current in-progress plan or design doc, so if you have any idea / improvements / patch, feel free to create a patch. I would be happy to help with reviews...

**Review by elek — APPROVED** [review]
+1. Let's test this feature.

Thanks the patch @adoroszlai and the review @cxorm

**Comment by elek** [comment]
I need to revert it temporary, as it's not possible to push to the master today:

```
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 12 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 1.93 KiB | 987.00 KiB/s, done.
Total 5 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: 3 of 3 required status checks are expected. At least 1 approving review is required by reviewers with write access.
To github.com:apache/ozone-go.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'github.com:apache/ozone-go.git'
```

My +1 still stand, and I will reapply this one after the initial import is reviewed.

**Pull request merged**
